name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # यहाँ हम गिटहब का थोड़ा पुराना और स्थिर सर्वर यूज़ कर रहे हैं जहाँ बिल्डोज़र बेस्ट चलता है

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good ccache automake autoconf libltdl-dev libtool pkg-config
        pip install --upgrade pip
        pip install --upgrade buildozer cython virtualenv sh

    - name: Build with Buildozer
      run: |
        rm -f buildozer.spec
        buildozer init
        
        # ऑटोमैटिकली स्पेसिफिकेशन फाइल में लाइसेंस एक्सेप्ट करना ताकि ये रुके नहीं
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        
        # बिना किसी एक्सटर्नल पाथ के फ्रेश और साइलेंट ऑटोमैटिक बिल्ड
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
